language: cpp

<<<<<<< HEAD
script:   
- cmake -H. -B_build
- cmake --build _build
notifications:
  email: false
services:
  - docker
script:
  - docker build -t logger .
=======
script:
- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install
- cmake --build _build
>>>>>>> 45730a3c6bd4887138f56be01f0cabaacee70bfd
